global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert-rules/rust-backend-alert-rules.yml

scrape_configs:
  - job_name: rust-backend
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - rust-backend:8080
    authorization:
      type: Bearer
      credentials: ${METRICS_ADMIN_TOKEN}
